-- ==========================================
-- ARMAN ENTERPRISES - DATABASE SCHEMA v3
-- ==========================================

-- 1. Create Customers Table
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    id_label TEXT DEFAULT 'GSTIN' CHECK (id_label IN ('GSTIN', 'AADHAAR')),
    id_value TEXT
);

-- 2. Create Vehicles Table
CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    vehicle_no TEXT UNIQUE NOT NULL
);

-- 3. Create Invoices Table
CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    invoice_no TEXT UNIQUE NOT NULL,
    date DATE NOT NULL,
    ewb_no TEXT,
    customer_id BIGINT REFERENCES customers(id) ON DELETE RESTRICT,
    vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE SET NULL,
    total_taxable_value NUMERIC(10, 2) NOT NULL,
    total_cgst NUMERIC(10, 2) NOT NULL,
    total_sgst NUMERIC(10, 2) NOT NULL,
    grand_total NUMERIC(10, 2) NOT NULL
);

-- 4. Create Invoice Items Table
CREATE TABLE invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    hsn TEXT,
    quantity NUMERIC(10, 2) NOT NULL,
    rate NUMERIC(10, 2) NOT NULL,
    cgst_percent NUMERIC(5, 2) DEFAULT 9.00,
    sgst_percent NUMERIC(5, 2) DEFAULT 9.00
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;

-- Lock down access so ONLY logged-in users (you) can read/write data
CREATE POLICY "Enable all access for authenticated users" ON customers FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON vehicles FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON invoices FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON invoice_items FOR ALL USING (auth.role() = 'authenticated');